language: go

go: 1.4
  
notifications:
  irc: 
    channels: 
      - "chat.freenode.net#seedstack-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    skip_join: true
    use_notice: true
    
install: go get gopkg.in/yaml.v2

script: go test -cover ./seed